{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArn }}
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Chart.Name }}
{{- end }}
